### ISSUE TITLE
Can not edit config to run on port 53? (function get_free_udp_port)

### ISSUE THREAD

**Issue by UNlDAN** [l-n-s/wireguard-install#29]
I edited the portion of the code to give me 53 for a random lookup so my final config has port 53 in it:

`function get_free_udp_port
{
    local port=$(shuf -i 053-053 -n 1)
    ss -lau | grep $port > /dev/null
    if [[ $? == 1 ]] ; then
        echo "$port"`

also tried

`function get_free_udp_port
{
    local port=$(shuf -i 053-053 -n 1)
    ss -lau | grep $port > /dev/null
    if [[ $? == 1 ]] ; then
        echo "53"`

And none of this works. In the end, I end up with this:

Try `iptables -h' or 'iptables --help' for more information.
Created symlink /etc/systemd/system/multi-user.target.wants/wg-quick@wg0.service → /lib/systemd/system/wg-quick@.service.
Job for wg-quick@wg0.service failed because the control process exited with error code.
See "systemctl  status wg-quick@wg0.service" and "journalctl  -xe" for details.
Client config --> /root/client-wg0.conf
Now reboot the server and enjoy your fresh VPN installation! :^)

Can someone help so I can install wireguard to Port 53? Seems like if I replace it with a 3 digit number, it works (053 doesn't work I tried)

**Comment by l-n-s** [comment]
You can make it easier, run it with environment variable SERVER_PORT=53

    SERVER_PORT=53 bash wireguard-install.sh

**Comment by UNlDAN** [comment]
Unfortunately that did not work either. 

Result is the same:


net.ipv4.ip_forward = 1                                     
net.ipv4.conf.all.forwarding = 1                            
net.ipv6.conf.all.forwarding = 1                            
Created symlink /etc/systemd/system/multi-user.ta           
rget.wants/wg-quick@wg0.service → /lib/systemd/sy           
stem/wg-quick@.service.                                     
Job for wg-quick@wg0.service failed because the c           
ontrol process exited with error code.                      
See "systemctl  status wg-quick@wg0.service" and            
"journalctl  -xe" for details.                              
Client config --> /root/client-wg0.conf                     
Now reboot the server and enjoy your fresh VPN in           
stallation! :^)                                             
root@WireguardP500:~#

**Comment by l-n-s** [comment]
See "systemctl status wg-quick@wg0.service" and
"journalctl -xe" for details.

**Comment by UNlDAN** [comment]
Result of the first command:

> 
> root@WireguardP500:~# systemctl status wg-quick@w                                             
> g0.service                                                                                    
> ● wg-quick@wg0.service - WireGuard via wg-quick(8                                             
>    Loaded: loaded (/lib/systemd/system/wg-quick@.                                             
>    Active: failed (Result: exit-code) since Thu 2                                             
>      Docs: man:wg-quick(8)                                                                    
>            man:wg(8)                                                                          
>            https://www.wireguard.com/                                                         
>            https://www.wireguard.com/quickstart/                                              
>            https://git.zx2c4.com/WireGuard/about/                                             
>            https://git.zx2c4.com/WireGuard/about/                                             
>   Process: 740 ExecStart=/usr/bin/wg-quick up wg0                                             
>  Main PID: 740 (code=exited, status=2)                                                        
>                                                                                               
> Mar 21 08:58:41 WireguardP500 wg-quick[740]: [#]                                              
> Mar 21 08:58:41 WireguardP500 wg-quick[740]: [#]                                              
> Mar 21 08:58:41 WireguardP500 wg-quick[740]: [#]                                              
> Mar 21 08:58:41 WireguardP500 wg-quick[740]: [#]                                              
> Mar 21 08:58:41 WireguardP500 wg-quick[740]: RTNE                                             
> Mar 21 08:58:41 WireguardP500 wg-quick[740]: [#]                                              
> lines 1-18...skipping...                                                                      
> ● wg-quick@wg0.service - WireGuard via wg-quick(8                                             
>    Loaded: loaded (/lib/systemd/system/wg-quick@.                                             
>    Active: failed (Result: exit-code) since Thu 2                                             
>      Docs: man:wg-quick(8)                                                                    
>            man:wg(8)                                                                          
>            https://www.wireguard.com/                                                         
>            https://www.wireguard.com/quickstart/                                              
>            https://git.zx2c4.com/WireGuard/about/                                             
>            https://git.zx2c4.com/WireGuard/about/                                             
>   Process: 740 ExecStart=/usr/bin/wg-quick up wg0                                             
>  Main PID: 740 (code=exited, status=2)                                                        
>                                                                                               
> Mar 21 08:58:41 WireguardP500 wg-quick[740]: [#]                                              
> Mar 21 08:58:41 WireguardP500 wg-quick[740]: [#]                                              
> Mar 21 08:58:41 WireguardP500 wg-quick[740]: [#]                                              
> Mar 21 08:58:41 WireguardP500 wg-quick[740]: [#]                                              
> Mar 21 08:58:41 WireguardP500 wg-quick[740]: RTNE                                             
> Mar 21 08:58:41 WireguardP500 wg-quick[740]: [#]                                              
> Mar 21 08:58:41 WireguardP500 systemd[1]: wg-quic                                             
> ● wg-quick@wg0.service - WireGuard via wg-quick(8) for wg0                                    
>    Loaded: loaded (/lib/systemd/system/wg-quick@.service; enabled; vendor preset: enabled)    
>    Active: failed (Result: exit-code) since Thu 2019-03-21 08:58:41 PDT; 51min ago            
>      Docs: man:wg-quick(8)                                                                    
>            man:wg(8)

**Comment by UNlDAN** [comment]
Second command:

> root@WireguardP500:~# journalctl -xe             
> Mar 21 09:49:33 WireguardP500 systemd[1226]: Star
> -- Subject: User manager start-up is now complete
> -- Defined-By: systemd                           
> -- Support: http://www.ubuntu.com/support        
> --                                               
> -- The user manager instance for user 0 has been 
> -- for starting have been started. Note that othe
> -- up or be started at any later time.           
> --                                               
> -- Startup of the manager took 38109 microseconds
> Mar 21 09:49:33 WireguardP500 systemd[1]: Started
> -- Subject: Unit user@0.service has finished star
> -- Defined-By: systemd                           
> -- Support: http://www.ubuntu.com/support        
> --                                               
> -- Unit user@0.service has finished starting up. 
> --                                               
> -- The start-up result is done

.

**Comment by UNlDAN** [comment]
@l-n-s  any comment on this? You can try with any Debian Distro and it will show this.

**Comment by l-n-s** [comment]
My Debian machine works fine. 

Have you tried to do a clean install? Either uninstall everything and remove all the config files (if you can). Or reinstall the OS.

**Comment by UNlDAN** [comment]
> My Debian machine works fine.
> 
> Have you tried to do a clean install? Either uninstall everything and remove all the config files (if you can). Or reinstall the OS.

Yes I have. Brand new Debian 9.0 and 9.8

**Comment by LiveChief** [comment]
Go to my profile and check out my wireguard script it should work fine

**Comment by l-n-s** [comment]
@LiveChief what is the problem here and how did you fix it? You just claim that your script works without explaining why.

**Comment by LiveChief** [comment]
My script is a little different than yours, it's little bit more customized and if u wanna find out how it's done just take a look at the script, 2 min later it should make sense it's pretty easy.

**Comment by l-n-s** [comment]
@LiveChief all your self-promoting messages here will be deleted, you have been warned. Forget about this repo and go bullshit somewhere else.

@UNlDAN will try to re-check it this weekend, but it looks that your system has a bad config file /etc/wireguard/wg0.conf for some reason.  I really advise you to retry a fresh installation, without /etc/wireguard/wg0.conf file.

**Comment by LiveChief** [comment]
Here cuck,

Enjoy the code...



    	echo "What port do you want WireGuard to listen to?"
	echo "   1) Default: 51820"
	echo "   2) Custom"
	echo "   3) Random [2000-65535]"
	until [[ "$PORT_CHOICE" =~ ^[1-3]$ ]]; do
		read -rp "Port choice [1-3]: " -e -i 1 PORT_CHOICE
	done
	case $PORT_CHOICE in
		1)
			SERVER_PORT="51820"
		;;
		2)
			until [[ "$SERVER_PORT" =~ ^[0-9]+$ ]] && [ "$SERVER_PORT" -ge 1 ] && [ "$SERVER_PORT" -le 65535 ]; do
				read -rp "Custom port [1-65535]: " -e -i 51820 SERVER_PORT
			done
		;;
		3)
			# Generate random number within private ports range
			SERVER_PORT=$(shuf -i2000-65535 -n1)
			echo "Random Port: $SERVER_PORT"
		;;
	esac

**Comment by UNlDAN** [comment]
Still not working unfortunately. I tried on AWS, GCP and Bare metal servers. Port 53 is a no go.
